on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  atl_buzz_build:
    name: 🔥 ATL Vibe Build + Log Drop
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Pull The BUZZO Source
        uses: actions/checkout@v4

      - name: ☕ Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 🛠️ Give gradlew Wings
        run: chmod +x gradlew

      - name: 🧪 Execute Build w/ ATL Flavor
        run: ./gradlew build --stacktrace --info | tee buzzo_build_log.txt

      - name: 📦 Zip APKs for Drop
        uses: actions/upload-artifact@v4
        with:
          name: 🔥 APK_Vibe_Pack
          path: app/build/outputs/apk/**/*.apk

      - name: 📄 Upload BUZZO Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: buzzo_build_log.txt

      - name: 🧠 Cache Gradle for Faster Buzzing
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: 🔔 Alert the Buzzo Nation (Optional Webhook)
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text":"❌ BUZZO BUILD FAILED! Time to vibe check. 🔊 \"Yo Fred, we got a drop!\""}' \
          https://your-webhook-url.com/notify  # Replace with your Slack, Discord, etc.

      - name: 🔊 Optional Voice Drop (BUZZO ATL)
        if: success()
        run: |
          echo "🗣️ Buzzo CI complete, Daddy Fred on deck! 💥 ATL energy secured. 🔒" > atl_voice_drop.txt

      - name: 🗂️ Upload Voice Drop Message
        uses: actions/upload-artifact@v4
        with:
          name: ATL-Voice-Note
          path: atl_voice_drop.txt

# 🛡️ FULLY CERTIFIED BUZZO STACK • POWERED BY VIBES • SIGNED: FDF 🔐